[package]
name = "dioxus-study"
version = "0.1.0"
authors = ["sakai-nako <80052740+sakai-nako@users.noreply.github.com>"]
edition = "2021"

[dependencies]
dioxus = { version = "0.6.0-alpha.2", features = ["web", "router"] }
wasm-bindgen = "=0.2.92"

# Debug
dioxus-logger = "0.5.1"
